### ISSUE TITLE
Refactor all border line with new mixin way

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1686]
https://github.com/ant-design/ant-design-mobile/pull/1682
- [x] List https://github.com/ant-design/ant-design-mobile/pull/1697

**Comment by paranoidjk** [comment]
cc @ustccjw @silentcloud @warmhug 

这个有空的都可以做一做，分组件的，直接 PR 好了。

**Comment by silentcloud** [comment]
嗯 先按照 wiki 那个对应着来

**Comment by sachin9891** [comment]
is There a way I can remove border for list please

**Comment by warmhug** [comment]
@sachin9891 You can overwrite the style.

**Comment by sachin9891** [comment]
I am not able to do it according to below link 
https://github.com/ant-design/ant-design-mobile/pull/1629
can you please give me a little example to how to do it 

versions 
react 16 
ant-desgin-mobile 2.x
react-native-web : 0.1.8,

**Comment by warmhug** [comment]
You are using web or react native version?

**Comment by sachin9891** [comment]
@warmhug 
I am react-native-web for making a mobile site 

https://github.com/necolas/react-native-web

**Comment by warmhug** [comment]
Uh. This is very simple, you need to solve by yourself

**Comment by lusan** [comment]
Hi @warmhug I am facing similar problem, it is definitely simple, if I try something like style={{style: value}}
However let us take an example of the problem I am facing,
Problem Statement: I want to **remove divider** from all { **Item** } in a { **List** }

After I inspected element, I saw that there is a **after pseudo class** with height: 1px with { Item } eg: .am-list-body div:not(:last-child) .am-list-line::after

How do I overrdide the style so that I do not have border bottom for { Item } in { List } ?

**Comment by lusan** [comment]
I was looking for a way something similar to how it's done in rn-custom-ui in antd-mobile-samples , by creating custom component wrapper on top of antd components without making direct change to the library code
Please check the below repo https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui
It's really cool how it's done for native, if we do something like for web would be really nice
_

**Comment by warmhug** [comment]
@lusan Your idea is good, but it may be harder to achieve. And rn-custom-ui does not seem to realize it.
