### ISSUE TITLE
Page Transition Animation

### ISSUE THREAD

**Issue by Enalmada** [ant-design/ant-design-mobile#2796]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When user clicks a link, the new page should slide in or out to reflect the direction the user is traveling.   
Look at Framework7 demo: https://framework7.io/react/kitchen-sink.html
Click any link in the kitchen sink to go forward and then click on the back button to return and pay attention to the animation. 

### What does the proposed API look like?
See Link component of Framework7 for proposed api: https://framework7.io/react/link.html
Specifically the back and animate parameters but I think you should take as much of Framework7 stuff as you can and get it into v2 so that Framework7 doesn't have anything that ant-design-mobile doesn't.

**Comment by awmleer** [comment]
Sorry for the late response since cleaning up the stale issues for v2 took me a lot of time. Seems v2 didn't implement this component and as for v5, there is still no plan. This is largely due to the different aims of antd-mobile and framework7. Currently I think the page transition should be implement in a hybrid app framework. It often needs to be used combine with routing, which is out of the range of a component library.
