### ISSUE TITLE
listView上拉滑动时，手指划出了浏览器区域后，listView中已经滑动到上方的item可以反弹回来

### ISSUE THREAD

**Issue by haomiaozhichen** [ant-design/ant-design-mobile#573]
#### 你做了什么？

手机微信扫码打开https://mobile.ant.design/kitchen-sink/refresh-control/ 网址；
注意：此时页面下方是浏览器区域，页面顶部标题栏已经不是浏览器区域了，
测试滑动效果，
当listview滑动到最底部时，继续上拉滑动；
手指向上滑动到页面顶部标题栏时，此时已经滑动到浏览器区域外面了，
listView中已经滑动到上方的item不能反弹回来

#### 你期待的结果是：
手指向上滑动到页面顶部标题栏时，listView中已经滑动到上方的item能反弹回来

#### 实际上的结果：

手指向上滑动到页面顶部标题栏时，此时已经滑动到浏览器区域外面了，
listView中已经滑动到上方的item不能反弹回来

猜测原因：手指划出了浏览器区域，touchEnd事件就不执行了，listView列表无法捕获到手指释放状态，所以listView中已经滑动到上方的item不能反弹回来；

备注：这是用于混合开发

**Comment by warmhug** [comment]
手指划出了浏览器区域，这时触发的事件还是 touchmove ，不会触发 touchend 或 touchcancel 事件。解决办法，一是：不要这么操作；二是：划出浏览器区域、native 抛出个事件，再想办法调用到 js 去执行 touchend ，但成本太高、真没必要这么做。

**Comment by 520Yanxiaofei** [comment]
@haomiaozhichen 您好，这个问题您解决了吗？我也遇到这个坑

**Comment by haomiaozhichen** [comment]
@520Yanxiaofei 解决了

**Comment by warmhug** [comment]
@haomiaozhichen 是怎么解决的？在 Android 上没这个问题

**Comment by haomiaozhichen** [comment]
已经解决，他们库升级了




发自网易邮箱大师
在2017年10月25日 10:55，warmhug 写道：

@haomiaozhichen 是怎么解决的？在 Android 上没这个问题

**Comment by warmhug** [comment]
> 他们库升级了

是谁的库？什么版本呢

**Comment by haomiaozhichen** [comment]
and mobile 库，最新版吧，你试试




发自网易邮箱大师
在2017年10月25日 17:37，warmhug 写道：

他们库升级了

是谁的库？什么版本呢

**Comment by warmhug** [comment]
涉及到问题的情形：

- iOS UIwebview 下（WKwebview 暂时未发现），Android 平台没问题
- antd-mobile 1.x http://1x.mobile.ant.design/components/refresh-control-cn/ 里 RefreshControl 组件；2.x 里 https://mobile.ant.design/components/pull-to-refresh/ 里 PullToRefresh 组件

相关描述和解决办法： 
https://github.com/facebook/react-native/issues/321  
https://segmentfault.com/q/1010000002943205

**Comment by ZLingC** [comment]
怎么在ie上以body作为容器时不能滚动加载

**Comment by Web-of-Dancer** [comment]
这个不是ant-design-mobile吗？移动端怎么会有IE浏览器！由華為手機發送--------原始郵件 --------主旨：Re: [ant-design/ant-design-mobile] listView上拉滑动时，手指划出了浏览器区域后，listView中已经滑动到上方的item可以反弹回来 (#573)寄件者：ZLinC 收件者：ant-design/ant-design-mobile 副本：Stephen W ,Comment 怎么在ie上以body作为容器时不能滚动加载



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ant-design/ant-design-mobile","title":"ant-design/ant-design-mobile","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ant-design/ant-design-mobile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ZLingC in #573: 怎么在ie上以body作为容器时不能滚动加载\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ant-design/ant-design-mobile/issues/573#issuecomment-452632118"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ant-design/ant-design-mobile/issues/573#issuecomment-452632118",

"url": "https://github.com/ant-design/ant-design-mobile/issues/573#issuecomment-452632118",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ZLingC** [comment]
兼容pc端的ie浏览器时，出现这样问题的

**Comment by ZLingC** [comment]
好的，👌
